name: publish mainline merges

on:
  push:
    branches:
      - mainline

jobs:
  publish:
    name: Publish merged commits

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate version
        id: genver
        uses: paulhatch/semantic-version@v3.2
        with:
          branch: "mainline"
          major_pattern: "!:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-mainline${increment}"
          short_tags: true
          bump_each_commit: false

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test and coverage report
        run: sbt test coverageReport

      - name: Codecov push report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: Publish Package
        run: sbt publish
        env:
          GH_ACTIONS_VER: ${{ steps.genver.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
