name: Incremental Publish

on:
  push:
    branches: [ mainline ]

jobs:
  build:
    name: Build/Test/Publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests
        run: sbt test

      - name: Create coverage report
        run: sbt coverageReport

      - name: Codecov push report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: Publish Package
        run: sbt publish
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
